  - name: Prettier Java Action
  uses: 'lukasmwerner/prettier_action_java@v1.1.1'
  with:
    # Commit message
    commit_message: # The Code has been prettified!
    # Commit options
    commit_options: # optional
    # File pattern used for `git add`
    file_pattern: # optional, default is *
    # Options for the `prettier` command
    prettier_options: # optional, default is --write **/*.java
    # Target branch for the changes
    branch: 
    # Running the script in dry mode just shows whether there are files that should be prettified or not
    dry: # optional
    # Specific version of prettier (by default just use the latest version)
    prettier_version: # optional
